language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
install:
  - npm i
script:
  - npm run cover
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
deploy:
  provider: npm
  email: "info@docfalcon.com"
  api_key:
    secure: "vmu5jmPYVQaDzV8xv1pwigX7bJrlxGrTCxYFNLl1qew/es9PWKYuCPgMDMeb7WlCwAHEqF2n5RhusFfv2WBptuGgI9bE5PlrkZQVhxBT1mlWXFCDGAhjlZbX/t/kpS8PBohtwviztTUWhW7AjiT8HjvUpLhHPW7m7373i27TRFIpJp0JGme9Lq9Glr8mhYcuhzuSLAmZsFu5qbOFz147oCMbHcMMY6OlGYwQf00ir4ty/M7vNS7zxMNRqP3wwKKU03GrjPojcNXK9VMFOenyqvl0hIlbUJdYtXG4Hu8ySredxZWEiTZmjL5w2VakEYsMOi9wLctvMJxkKCulH5aJ2QoTbzDg5se6Xkyv7KpU6jZVCENA8+3Pns85q7rtRWXxWNEJa01xMuPL/5RiZLzbI5WdbPb+WACWpAuNDyjDJ5rJR71SJe6z1lcAu6ugbQT93OXIfljVWBf97C+u76ialwVV1F7n8Xkto4X5L7BAOl5oAAv+vNxyqjQOGcE97st/25s6KDO2mw1swUBPcpoD2V0l40Ri2JFCfDITg4Ai8uXt2dj88iiwrWdNdQ8lOfE+0Q+wo70ZLxtAsvmcrm3n380sOQsNkoyypW+MIiCfQaE+dXeJMinFJLIi4/ZF6BqDPKJ61R6c75quGSy7sCp/bFmrObvgfTQllAWQtu8gEbE="
  on:
    all_branches: true

