language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
install:
  - npm i
script:
  - npm run cover
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
deploy:
  provider: npm
  email: "info@docfalcon.com"
  api_key:
    secure: "jP8zJNqERz1n+gXQIDfNTqo2koXLpn19PIWTzG+d1UtgFGCI1+FrMRGMPzsG2XwkTUMCav5qLqdqjIYvV6MGMxoLsxfog4qP1OE6AiQexrZzWnUM7OunjG2KCexRp7VzF5wmURyRhbt/JIn1pSEwMeQxWGOBOAPjTuc+KTs0KzqQraOyRbl766S16w+dZGV14E8QrOxD5xdYNgXTaUaYzuXYJ9mBS1+DM+jexb1+30hmU2HWMUO6t8Hhh410bSN72PxhDvS8AF/b1QR4ba8QkQNW7GSzN8ROJWbI0QL296U/dJ7A9gPVuNod2xy7SZdj3nFjFbp6H/pu2sQcWPRdBwKjpP7kOCvyJUGStxe6BzK3iaULtIEX6OYlblE6OZ6+/k6hWGH46uzARyUxcB86EEllaouIFjHKcEZytJzXUvxLL9m5Cj1yO1JtDssYiQHTkpMILGUQGDB6nFA4dmO1sTDBEwLBFoQ2IVhj6d/kPg0ZHWxR9+4A299SZhJ3a3OWTyWjGZpPDnp0JAylHOF8uIYOyshdj8IM7ehymDQoQHUf8S3vBM1bu1Xou/5jHAMM0JDS6Z4EhM4OTW9EeJSgPRbTDBffJnWE+6tuhl7ipybSoExw7Y6e+cI91Hww6Iij4aheota+wKYosF86FW9VyG+fUfbuaaAfum6Upe3nqd0="
  on:
    branch: production

